[tool.poetry]
name = "python-fluent-breaking-standards"
version = "0.1.0"
description = ""
authors = ["RootShinobi"]
readme = "README.rst"
include = [
  { path = "fluent.syntax" },
  { path = "fluent.runtime" }
]

[tool.poetry.dependencies]
fluent-syntax = { path = "./fluent.syntax" }
fluent-runtime = { path = "./fluent.runtime" }
